version: "3.9"
services:

  api:
    build: ./api
    ports:
      - "6900:${PORT}"
    environment:
     - PG_CON=postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
     - PORT
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   image: postgres:latest
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
