# This is a basic workflow to help you get started with Actions

name: pullRequestMain

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
env:
  PORT: 5432
  APIPORT: 6900
  POSTGRES_HOST: pg
  POSTGRES_PASSWORD: admin
  POSTGRES_USER: admin
  POSTGRES_DB: producenten

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build docker container
        run: docker-compose build
        
      - name: Run docker container
        run: docker-compose up -d
        
      - name: Npm install
        run: |
          cd api/src
          npm ci
          
      - name: Run test
        run: |
          cd api/src
          npm test

